### PR TITLE
Revise farmer income calculation (Change results in tableB and table1…

### PR DESCRIPTION
**Pull request by AnHaTruong**
…2). Update TODO.

### CODE REVIEW

**Comment by MinhHaDuong** [comment]
The arguments list are too long, you should use the ParameterObject programming pattern:  http://wiki.c2.com/?ParameterObject

To do so, put the parameters that go together in a namedtuple.
namedtuple is in the standard library, so add "from collections import namedtuple"  in parameter.py
https://docs.python.org/3/library/collections.html#collections.namedtuple
https://pythontips.com/2015/06/06/why-should-you-use-namedtuple-instead-of-a-tuple/
https://pythonconquerstheuniverse.wordpress.com/2010/10/23/an-arguments-container-pattern/
http://techqa.info/programming/question/12716258/Passing--argument-lists--as-a-namedtuple-in-python

**Comment by AnHaTruong** [comment]
Thanks. I'll do it later. I am working with Bewhere now. Will meet Piera in
1h.

**Comment by MinhHaDuong** [comment]
The code in TableB duplicates the code to compute the profit.
The method  profit()  could return a t-uple (profit, income, wages, ...)
so that in TableB you just have to unpack the result, not recode it.

**Comment by MinhHaDuong** [comment]
I like to have tests in the code that complain if the key findings of our paper don't check out.
Add an  assert  statement so that the run breaks with an error if the farmers loose money.

**Comment by MinhHaDuong** [comment]
I am working on the long arguments list now.
Using a dictionary not a namedtuple, because we want mutability for sensitivity analysis

**Pull request merged**
